server:
  port: 8761
  shutdown: graceful


spring:
  application:
    name: eureka-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

# ???? ?? ??? ???? ????
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
